apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-fastapi-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-fastapi-app
  template:
    metadata:
      labels:
        app: my-fastapi-app
    spec:
      containers:
      - name: my-fastapi-container
        image: my-fastapi-image:latest
        ports:
        - containerPort: 8000
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: LOG_FILE
          value: "/app/app.log"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.ini
          subPath: config.ini
      volumes:
      - name: config-volume
        configMap:
          name: my-fastapi-config
