apiVersion: v1
kind: Service
metadata:
  name: my-fastapi-service
spec:
  selector:
    app: my-fastapi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30000 # Example node port
  type: NodePort
